## TechSim Assignment 1 


In [1]:
import numpy as np
import pandas as pd

In [2]:
# Create a DataFrame using list
columns = ['Name', 'Age', 'Mobile Number', 'Email']
data = [
        ['Sara', 21, 9132454356, 'sara@gmail.com'], 
        ['Ram', 28, 9203949283, 'ram@gmail.com'], 
        ['Suman', 23, 2392838495, 'suman@gmail.com'],
        ['Rosh', 29, 9283742800, 'rosh@gmail.com']
       ] 
df = pd.DataFrame(data, columns= columns)

In [3]:
df

Name  Age  Mobile Number            Email
0   Sara   21     9132454356   sara@gmail.com
1    Ram   28     9203949283    ram@gmail.com
2  Suman   23     2392838495  suman@gmail.com
3   Rosh   29     9283742800   rosh@gmail.com

In [4]:
# Columns name of the dataframe
df.columns

Index(['Name', 'Age', 'Mobile Number', 'Email'], dtype='object')

In [5]:
# Select a particular value from a DataFrame and replace it wwith the new value
df.replace(to_replace='Suman', value='Suresh', inplace=True)
df

Name  Age  Mobile Number            Email
0    Sara   21     9132454356   sara@gmail.com
1     Ram   28     9203949283    ram@gmail.com
2  Suresh   23     2392838495  suman@gmail.com
3    Rosh   29     9283742800   rosh@gmail.com

In [6]:
# Create a new column in pandas dataframe based on the existing columns
df['New Age'] = df['Age'] + 10
df

Name  Age  Mobile Number            Email  New Age
0    Sara   21     9132454356   sara@gmail.com       31
1     Ram   28     9203949283    ram@gmail.com       38
2  Suresh   23     2392838495  suman@gmail.com       33
3    Rosh   29     9283742800   rosh@gmail.com       39

In [7]:
# Create a array that have six random integers between 10 and 30
array = np.random.randint(10,30,size=(6))
array

array([12, 18, 18, 21, 19, 20])

In [8]:
# Create a 5*5 array with random values and find the minimum and maximum values
array = np.random.randint(25,size=(5,5))
print('5*5 array with random values is: \n {}'.format(array))
print(f'Minimum value in a array is: {array.min()}')
print(f'Maximum value in a array is: {array.max()}')

5*5 array with random values is: 
 [[24 16 13  0 24]
 [ 6  1 20 15 10]
 [ 5  6  7 11  7]
 [ 8  8 14 15 21]
 [21 16 16 20 13]]
Minimum value in a array is: 0
Maximum value in a array is: 24
